# Generated by Django 2.0.7 on 2020-05-10 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='post_time',
        ),
    ]
